version: '3'
services:
  mlflow-server:
    build: 
      context: .
      dockerfile: ./mlflow_server/Dockerfile
    volumes:
      - mlflow-data:/mlflow_server
    ports:
      - "5000:5000"
  training:
    build: 
      context: .
      dockerfile: ./training/Dockerfile
    environment: 
      - MLFLOW_TRACKING_URI=http://mlflow-server:5000
    depends_on:
      - mlflow-server
    volumes:
      - mlflow-data:/mlflow_server
        
volumes:
  mlflow-data:
